name: Android APK CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        run: |
          sudo mkdir -p $ANDROID_SDK_ROOT
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools

          if [ ! -d "latest" ]; then
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
            unzip -q tools.zip
            mv cmdline-tools latest
          fi

          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Setup Gradle (manual, как у тебя)
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl

          curl -L https://services.gradle.org/distributions/gradle-8.3-bin.zip -o gradle.zip
          unzip -q gradle.zip
          mv gradle-8.3 gradle
          chmod +x gradle/bin/gradle

      - name: Build APK
        run: |
          ./gradle/bin/gradle assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
